var am={};am.Observable=Class.create({fire:function(event_name){if(!event_name||!this._event_cache){return;}
var listeners=this._event_cache[event_name];if(!listeners){return;}
var args=$A(arguments).slice(1);for(var i=0,len=listeners.length;i<len;i++){listeners[i].apply(this,args);}},observe:function(event_name,listener){if(typeof(event_name)!=='string'){for(var name in event_name){this.observe(name,event_name[name]);}}else{if(!event_name||!listener){return;}
if(!this._event_cache){this._event_cache={};}
var listeners=this._event_cache[event_name]||[];if(!listeners.include(listener)){listeners.push(listener);}
this._event_cache[event_name]=listeners;}},stopObserving:function(event_name,listener){if(!this._event_cache){return;}
if(!event_name){delete this._event_cache;}else if(!listener){delete this._event_cache[event_name];}else{var listeners=this._event_cache[event_name];if(!listeners){return;}
listeners=listeners.without(listener);if(listeners.length===0){delete this._event_cache[event_name];}else{this._event_cache[event_name]=listeners;}}}});am.PropList=Class.create({initialize:function(src){this.rows=Object.isArray(src)?src.clone():[];this.column={};this.header=this.rows.shift();if(this.header){for(var i=0,len=this.header.length;i<len;i++){this.column[this.header[i]]=i;}}},getHeader:function(){return this.header||[];},getRecord:function(index){return(this.rows[index]||null);},getValue:function(index,key){var row=this.rows[index];var column=this.column[key];if(row&&(column!=null)){return row[column];}else{return'';}},getRecordNum:function(){return(this.rows.length||0);},getJsArray:function(order){if(!order){return this.rows;}
return this.rows.map(function(row){return order.map(function(key){var column=this.column[key];return(typeof(column)==='number')?row[column]:'';},this);},this);},searchRecord:function(key,value){var column=this.column[key];if(column==null){return-1;}
for(var i=0;i<this.rows.length;i++){if(this.rows[i][column]===value){return i;}}
return-1;}});am.Server=Class.create({initialize:function(){this.id=0;this.clients=[];this.data={};this.cache={};},destroy:function(){delete this.data;delete this.cache;delete this.master;delete this.clients;},checkAlive:function(exclude){var alives=[];for(var i=0,len=this.clients.length;i<len;i++){try{var client=this.clients[i];if((client!==exclude)&&client.alive()){alives[alives.length]=client;}}catch(e){}}
this.clients=alives;},register:function(client){if(!this.master){this.master=client;}
if(!this.clients.include(client)){this.checkAlive();var seniors=this.clients.clone();this.clients.push(client);seniors.each(function(client){client.fire('amapp:append');});}},unregister:function(client){if(client===this.master){this.cleanup();}else{if(this.clients.include(client)){this.checkAlive(client);this.clients.each(function(client){client.fire('amapp:remove');});}}},cleanup:function(){this.checkAlive(this.master);this.clients.each(function(client){client.fire('amapp:break');});this.destroy();},getId:function(){return this.id++;},getData:function(){return this.data;},getMaster:function(){return this.master;},setData:function(data,win){if((win==null)||(win==window)){Object.extend(this.data,data||{});}else{Object.extend(this.data,Object.deepCopy(data));}},clearData:function(){for(var key in this.data){delete this.data[key];}},getCache:function(){return this.cache;},getAllClients:function(){this.checkAlive();return this.clients.clone();},getChildClients:function(base){this.checkAlive();return this.clients.collect(function(client){for(var a=client;a;a=a.parent){if(a.parent===base){return client;}}
return null;}).compact();},getIs:function(){return window.is;}});am.Client=Class.create(am.Observable,{win:window,parent:null,server:null,quirksMode:false,standardMode:false,contentBox:false,borderBox:false,MaxZIndex:100,Modules:{Browser:['browser.js'],Core:['Browser','modules/core.js'],Drag:['modules/drag.js'],Panel:['Drag','modules/panel.js'],Vpop:['Panel','modules/vpop.js'],XCommon:['lib/dhtmlxCommon/dhtmlxcommon.js','modules/xcommon.js'],XTree:['XCommon','lib/dhtmlxTree/dhtmlxtree.js','lib/dhtmlxTree/dhtmlxtree_ed.js','modules/xtree.js'],XGrid:['XCommon','lib/dhtmlxGrid/dhtmlxgrid.js','lib/dhtmlxGrid/dhtmlxgridcell.js','modules/xgrid.js'],EXGrid:['XGrid','lib/dhtmlxGrid/dhtmlxgrid_drag.js','lib/dhtmlxGrid/dhtmlxgrid_srnd.js','lib/dhtmlxGrid/dhtmlxgrid_mcol.js','lib/dhtmlxGrid/dhtmlxgrid_hmenu.js'],Pulldown:['lib/hmenu/hmenu.js','modules/pulldown.js'],ListBox:['modules/listbox.js'],Layout:['Drag','modules/layout.js'],CKEditor4:['lib/ckeditor4/ckeditor.js','modules/new_editor2.js'],Calendar:['lib/dhtmlxCalendar/dhtmlxcalendar.js','modules/calendar.js'],ContextMenu:['modules/contextmenu.js'],DnDUploader:['modules/dnduploader.js'],Debug:['modules/debug.js']},initialize:function(data,options){this.loadedScripts=[];if(data){this.server=new am.Server();this.server.setData(data);}else{if(opener&&!opener.closed&&opener.amapp){this.server=opener.amapp.server;}else if(parent&&!parent.closed&&parent.amapp){this.server=parent.amapp.server;this.parent=parent.amapp;}}
this.name='am_interface_no_'+this.server.getId();this.server.register(this);this.master=this.server.getMaster();window.amdata=this.server.getData();window.amcache=this.server.getCache();window.is=this.server.getIs();if(window.is){window.is=Object.clone(window.is);}
Event.observe(window,'load',this.onLoad.bind(this));Event.observe(window,'unload',this.onUnload.bind(this));this.observe('amapp:break',this.onBreak.bind(this));if(options){if(options.KeyboardShortcut){document.observe('keypress',this.onKeyPress.bind(this));document.observe('keydown',this.onKeyDown.bind(this));this._keyboard_shortcut_enabled=true;}}},destroy:function(){this.stopObserving();delete this.server;delete this.parent;delete this.loadedScripts;},onLoad:function(){this.detectDisplayMode();this.fire('amapp:load');if(typeof(start)==='function'){start();}},onUnload:function(){this.fire('amapp:destroy');this.server.unregister(this);this.destroy();},onBreak:function(){delete this.parent;this.server=new am.Server();this.server.register(this);this.master=this.server.getMaster();window.amdata=this.server.getData();window.amcache=this.server.getCache();},loadScript:function(url){if(this.loadedScripts.include(url)){return;}
if(amdata.gen&&amdata.gen.BUILDID){url=url+'?'+amdata.gen.BUILDID;}
document.write('<script type="text/javascript" src="'
+url+'"><'+'/script>');this.loadedScripts.push(url);},require:function(){for(var i=0,len=arguments.length;i<len;i++){this.requireOne(arguments[i]);}},requireOne:function(module){if(module.endsWith('.js')){this.loadScript(module);}else{if(module==='Browser'){if(window.is){return;}}else if(module==='Vpop'){for(var app=this;app;app=app.parent){if(app.win.amvpop&&app.win.ammsg){window.amvpop=app.win.amvpop;window.ammsg=app.win.ammsg;return;}}}else if(module==='Pulldown'){window._dynarch_menu_url=amdata.url.js+'lib/hmenu/';if(window.parent){window.parent._dynarch_menu_url=window._dynarch_menu_url;}}
(this.Modules[module]||[]).each(function(src){if(src.endsWith('.js')){this.loadScript(amdata.url.js+src);}else{this.requireOne(src);}},this);}},detectDisplayMode:function(){if(document.compatMode!=null){this.quirksMode=!!(document.compatMode==='BackCompat');}else if(document.doctype){this.quirksMode=!!(!document.doctype.publicId||((document.doctype.publicId.match(/Transitional/i)||document.doctype.publicId.match(/Frameset/i))&&!document.doctype.systemId));}else{var box=new Element('div');box.style.width='1';document.documentElement.appendChild(box);this.quirksMode=!!(box.clientWidth===1);document.documentElement.removeChild(box);}
this.standardMode=!this.quirksMode;if(Prototype.Browser.IE){this.contentBox=this.standardMode;this.borderBox=this.quirksMode;}else{if(is.safari3up&&(is.sf_ver>=3.1)&&(is.sf_ver<5.1)){var boxSizing='content-box';}else{var boxSizing=document.documentElement.getStyle(Prototype.Browser.Gecko?'-moz-box-sizing':'box-sizing');}
if(boxSizing==='content-box'){this.contentBox=true;}else if(boxSizing=='border-box'){this.borderBox=true;}}},getViewWidth:function(){if(is.applewebkit||is.opera){return window.innerWidth;}else{if(this.quirksMode){return document.body.clientWidth;}else{return document.documentElement.clientWidth;}}},getViewHeight:function(){if(is.applewebkit||is.opera){return window.innerHeight;}else{if(this.quirksMode){return document.body.clientHeight;}else{return document.documentElement.clientHeight;}}},getDocumentWidth:function(){if((is.ie||is.fx)&&this.quirksMode){return document.body.scrollWidth;}else{return document.documentElement.scrollWidth;}},getDocumentHeight:function(){if((is.ie||is.fx)&&this.quirksMode){return document.body.scrollHeight;}else{return document.documentElement.scrollHeight;}},getRenderWidth:function(){return Math.max(this.getViewWidth(),this.getDocumentWidth());},getRenderHeight:function(){return Math.max(this.getViewHeight(),this.getDocumentHeight());},getScrollTop:function(){return window.pageYOffset||document.documentElement.scrollTop||document.body.scrollTop;},getScrollLeft:function(){return window.pageXOffset||document.documentElement.scrollLeft||document.body.scrollLeft;},getAllClients:function(){return this.server.getAllClients();},getChildClients:function(){return this.server.getChildClients(this);},timeout:function(){this.unfreeze();if(typeof(window.ammsg)==='object'){if((typeof(amtop)==='object'||typeof(amtop)==='function')&&amtop.mainWindowControl&&amtop.mainWindowControl.disattach){amtop.mainWindowControl.disattach("beforeUnload");}
ammsg.showAlert(ammsg.ERROR,'','GENERAL0080',null,this.relocateAfterTimeout.bind(this));}else{alert('session timeout.');this.relocateAfterTimeout();}},relocateAfterTimeout:function(status,master){if(!amdata||!amdata.url||!amdata.url.index){return;}
if(master||(this.master===this)){location.href=amdata.url.index;}else if(this.server.getChildClients(this.master).include(this)){this.master.relocateAfterTimeout(0,true);}},getFormElements:function(){var elements=$A(document.getElementsByTagName('INPUT'));elements=elements.concat($A(document.getElementsByTagName('SELECT')));elements=elements.concat($A(document.getElementsByTagName('TEXTAREA')));elements=elements.concat($A(document.getElementsByTagName('BUTTON')));return elements;},lock:function(recursive){if(this.locked){return;}
this.lockedElements=this.getFormElements().select(function(element){if(element&&!element.disabled){element.disabled=true;return true;}});if(recursive!==false){this.getChildClients().each(function(c){c.lock(false);});}
this.locked=true;},unlock:function(recursive){if(!this.locked){return;}
for(var i=0,len=this.lockedElements.length;i<len;i++){this.lockedElements[i].disabled=false;}
delete this.lockedElements;if(recursive!==false){this.getChildClients().each(function(c){c.unlock(false);});}
this.locked=false;},tmpunlock:function(){if(!this.locked){return;}
for(var i=0,len=this.lockedElements.length;i<len;i++){this.lockedElements[i].disabled=false;}},relock:function(){if(!this.locked){return;}
for(var i=0,len=this.lockedElements.length;i<len;i++){this.lockedElements[i].disabled=true;}},forceLock:function(){var elements=this.getFormElements();for(var i=0,len=elements.length;i<len;i++){elements[i].disabled=true;}},clearLock:function(){var elements=this.getFormElements();for(var i=0,len=elements.length;i<len;i++){elements[i].disabled=false;}},refreshData:function(data){this.server.clearData();this.server.setData(data,this.win);},alive:function(){return true;},freeze:function(){if(this.parent){this.parent.freeze();return;}
if(this.frozen){return;}
this.barrier=document.body.appendChild(new Element('div'));this.barrier.setStyle({position:'absolute',top:0,left:0,width:this.getRenderWidth()+'px',height:this.getRenderHeight()+'px',zIndex:10000,opacity:0,backgroundColor:'white'});this.frozen=true;if(this.unfreezeTimer){clearTimeout(this.unfreezeTimer);}
this.unfreezeTimer=setTimeout(this.unfreeze.bind(this),5*60*1000);},unfreeze:function(){if(this.parent){this.parent.unfreeze();return;}
if(!this.frozen){return;}
document.body.removeChild(this.barrier);delete this.barrier;this.frozen=false;if(this.unfreezeTimer){clearTimeout(this.unfreezeTimer);this.unfreezeTimer=null;}},onKeyDown:function(ev){if(this.frozen){return;}
if(window.amvpop&&(amvpop.getVpopNum()>0)){return;}
var el=ev.element();if(el.isInputElement&&el.isInputElement()){return;}
if(ev.charCode!=null&&ev.charCode!=0){return;}
var force_stop=false;var key;switch(ev.keyCode){case Event.KEY_DELETE:key='Delete';break;case Event.KEY_BACKSPACE:force_stop=true;if(is.mac){key='Delete';}
break;default:break;}
if(key){for(var client=this;client.parent;client=client.parent);if(client.doKey(key)){ev.stop();force_stop=false;}}
if(force_stop){ev.stop();}},onKeyPress:function(ev){if(this.frozen){return;}
if(window.amvpop&&(amvpop.getVpopNum()>0)){return;}
var el=ev.element();if(el.isInputElement&&el.isInputElement()){return;}
var code=(ev.charCode!=null)?ev.charCode:ev.keyCode;if((code<33)||(126<code)){return;}
if(ev.ctrlKey||ev.metaKey||ev.altKey){return;}
for(var client=this;client.parent;client=client.parent);if(client.doKey(String.fromCharCode(code))){ev.stop();}},doKey:function(code){var childs=this.getChildClients();for(var i=0,len=childs.length;i<len;i++){if(childs[i].doKey(code)){return true;}}
if(this.shortcuts){var shortcut=this.shortcuts[code];if(shortcut&&(typeof(shortcut.method)==='function')){shortcut.method();return true;}}
return false;},setKeyboardShortcut:function(shortcuts){this.shortcuts=Object.extend(this.shortcuts||{},shortcuts);},getKeyboardShortcut:function(){var shortcuts={};if(this.shortcuts){for(var key in this.shortcuts){shortcuts[key]=this.shortcuts[key].brief;}}
this.getChildClients().each(function(child){Object.extend(shortcuts,child.getKeyboardShortcut());});return shortcuts;},enabledKeyboardShortcut:function(){return!!this._keyboard_shortcut_enabled;}});(function(){window.amapp=new am.Client(amConfig.data,amConfig.options);amapp.require.apply(amapp,['Core'].concat($w(amConfig.modules||'')));})();
